Repository kilnfi/cosmos-validator-watcher, pull requests merged in 2024-11, with the labels that each got.

#85 feat: add support for slashing parameters and missed blocks per signing window
  pkg/app/flags.go
  pkg/app/run.go
  pkg/crypto/utils.go
  pkg/metrics/metrics.go
  pkg/watcher/slashing.go
  pkg/watcher/slashing_test.go
  pkg/watcher/types.go
  pkg/watcher/validators.go
  pkg/watcher/validators_test.go
Labels: feature

#86 feat: auto detect cosmos modules
  pkg/app/run.go
Labels: feature

#87 feat: add shortcut for log-level=debug
  README.md
  pkg/app/flags.go
  pkg/app/run.go
Labels: feature

#88 fix: add node info on all logs
  pkg/rpc/node.go
Labels: fix

#90 chore: simplify latestBlock variable in block watcher
  README.md
  pkg/watcher/block.go
Labels: chore, skip-changelog
